name: Formatting

on: [push]

jobs:
  format:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cmake_format
      run: |
        pip install cmake-format
    - name: Checks the code formatting
      run: |
        cmake-format -i module/pluginval.cmake
        cmake-format -i tst/plugin_verification/CMakeLists.txt
        git diff --exit-code
